### ISSUE TITLE
Hey not an issue just a question.

### ISSUE THREAD

**Issue by tapickell** [jdavis92/gcloud-builder-test#1]
Hi, I was searching Github for other people that may be using gcp cloudbuild to test an Elixir/Phoenix application. Your example repo here is one of the best ones I have found.
I was wondering if you ever got this to run tests correctly.
I am new to GCP and am having an issue figuring out how to get this to work like I would travis or circleci.
the issue I run into is that postgres is not available when I run tests.
I like your approach of waiting for the DB to start.
I have tried this in my own test project but still the application gets a connection refused. :(
I appreciate any information you could provide that might assist me in further understanding how to make this CI work with Elixir applications.
Thank you.

**Comment by jdav-dev** [comment]
I did get this build working after some frustration.  It still works, too.  I was just able to run the build.  I will say that my team ended up not using GCP Cloud Build.  It didn't have many features (dependency caching, build artifacts, for example) of other CI tools like CircleCI and GitLab CI.

As you can see in this screenshot, dd017ba6bf0209abda210bcb15fd47b6d3d02696 was the first commit where the build worked.  After that, I got fce83fd695ab138012e395383e1c2c21b0c56bbb and d4c29c56158275bc8f4a60d4db2388df4b7c16e0 to build from cached docker images, which shaved ~20 seconds off the build time.

![Screenshot from 2020-01-23 09-36-48](https://user-images.githubusercontent.com/18429247/72993785-e19e1a80-3ded-11ea-88a6-cebd71544196.png)

As far as the database config goes, the important things to note are in the builder config where the Postgres container is named with `--name=postgres`:

https://github.com/jdavis92/gcloud-builder-test/blob/d4c29c56158275bc8f4a60d4db2388df4b7c16e0/cloudbuild.yaml#L8-L11

And where the tests are configured to connect to the database at `hostname: "postgres"`:

https://github.com/jdavis92/gcloud-builder-test/blob/d4c29c56158275bc8f4a60d4db2388df4b7c16e0/config/test.exs#L12-L19

That's what I can think of to check without seeing your test project.  If that doesn't solve your issue, is it hosted somewhere I can take a look?

**Comment by tapickell** [comment]
Awesome, thank you.
I think that hostname is what I am missing.
I feel you about the lack of features compared to CircleCi
I want to run Dialyzer on every PR but it takes forever and I don't see how to cache the plts
